[colors]
foreground    = "#DBC3A3"
background    = "#072626"
cursor_bg     = "#DBC3A3"
cursor_border = "#DBC3A3"
cursor_fg     = "#292522"
selection_bg  = "#403A36"
selection_fg  = "#DBC3A3"
ansi = [
  "#34302C",
  "#BD8183",
  "#78997A",
  "#D8D3Fc",
  "#7F91B2",
  "#B380B0",
  "#7B9695",
  "#24CE00"
]
brights = [
  "#867462",
  "#D47766",
  "#85B695",
  "#EBC06D",
  "#0FDFAF",
  "#CF9BC2",
  "#89B3B6",
  "#DBC3A3"
]
