[colors]
foreground    = "#D8D1C6"
background    = "#050052"
cursor_bg     = "#D8D1C6"
cursor_border = "#D8D1C6"
cursor_fg     = "#292522"
selection_bg  = "#403A36"
selection_fg  = "#D8D1C6"
ansi = [
  "#34302C",
  "#BD8183",
  "#78997A",
  "#D8D3FC",
  "#7F91B2",
  "#B380B0",
  "#7B9695",
  "#C1A78E"
]
brights = [
  "#867462",
  "#D47766",
  "#2DFF00",
  "#FAF051",
  "#32EAFF",
  "#CF9BC2",
  "#89B3B6",
  "#D8D1C6"
]
